-- PROJETO_LOGICO_BDD:
DROP DATABASE IF EXISTS TesteBanco2;

CREATE DATABASE TesteBanco2;
USE TesteBanco2;

CREATE TABLE ADMINISTRADORES (
    ID INT AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Email VARCHAR(35) NOT NULL UNIQUE,
    CNPJ CHAR(14) NOT NULL UNIQUE,
    Senha VARCHAR(216),
    Data_Criacao DATETIME,
    Adm_Disponivel BIT,
    PRIMARY KEY (ID)
);

CREATE TABLE GM (
    ID_GM INT AUTO_INCREMENT PRIMARY KEY,
    Email_GM VARCHAR(35) NOT NULL,
    Codigo_Acesso_GM VARCHAR(13),
    Nome_GM VARCHAR(50) NOT NULL,
    Funcao VARCHAR(35) NOT NULL,
    Telefone_GM VARCHAR(15),
    Senha_GM VARCHAR(216),
    FK_ADM_ID INT,
    UNIQUE (Codigo_Acesso_GM, Email_GM, Telefone_GM),
    CONSTRAINT FK_GM_2 FOREIGN KEY (FK_ADM_ID) REFERENCES ADMINISTRADORES (ID) ON DELETE CASCADE
);

CREATE TABLE MESAS (
    ID_Mesa INT AUTO_INCREMENT PRIMARY KEY,
    FK_ADM_ID INT NOT NULL,
    FK_GM_ID_GM INT,
    Nome_Mesa VARCHAR(50),
    QuantidadeMax_Jog INT NOT NULL,
    Horario_Inicio DATETIME NOT NULL,
    Horario_Fim DATETIME,
    Proxima_Sessao DATETIME NOT NULL,
    Ultima_Sessao DATETIME,
    Anotacoes TEXT,
    Duracao DATETIME,
    Mesa_Disponivel BIT,
    CONSTRAINT FK_MESAS_2 FOREIGN KEY (FK_ADM_ID) REFERENCES ADMINISTRADORES (ID),
    CONSTRAINT FK_MESAS_3 FOREIGN KEY (FK_GM_ID_GM) REFERENCES GM (ID_GM)
);

CREATE TABLE JOGADORES (
    ID_jogador INT AUTO_INCREMENT PRIMARY KEY,
    Email_Jogador VARCHAR(35) UNIQUE,
    Nome_Jogador VARCHAR(50) NOT NULL,
    Telefone_Jogador VARCHAR(15)
);

CREATE TABLE FICHA (
    ID_Ficha INT AUTO_INCREMENT PRIMARY KEY,
    FK_JOGADORES_ID INT,
    Nome_Personagem VARCHAR(50),
    Raca_Personagem VARCHAR(20),
    Classe_Personagem VARCHAR(20),
    Criador_Original VARCHAR(50) NOT NULL,
    Ativa INT,
    Atribuida BIT,
    CONSTRAINT FK_FICHA_2 FOREIGN KEY (FK_JOGADORES_ID) REFERENCES JOGADORES (ID_jogador) ON DELETE SET NULL
);

CREATE TABLE MESA_JOGADOR (
    FK_MESAS_ID_Mesa INT,
    FK_JOGADORES_ID_Jogador INT,
    CONSTRAINT FK_MESA_JOGADOR_1 FOREIGN KEY (FK_MESAS_ID_Mesa) REFERENCES MESAS (ID_Mesa) ON DELETE CASCADE,
    CONSTRAINT FK_MESA_JOGADOR_2 FOREIGN KEY (FK_JOGADORES_ID_Jogador) REFERENCES JOGADORES (ID_jogador)
);

CREATE TABLE MESA_FICHA (
    FK_MESAS_ID_Mesa INT,
    FK_FICHA_ID_Ficha INT UNIQUE,
    CONSTRAINT FK_MESA_FICHA_1 FOREIGN KEY (FK_MESAS_ID_Mesa) REFERENCES MESAS (ID_Mesa) ON DELETE CASCADE,
    CONSTRAINT FK_MESA_FICHA_2 FOREIGN KEY (FK_FICHA_ID_Ficha) REFERENCES FICHA (ID_Ficha
