/* PROJETO_LOGICO_BDD: */
DROP DATABASE TesteBanco2

CREATE DATABASE TesteBanco2
USE TesteBanco2

CREATE TABLE ADMINISTRADORES (
    ID INT IDENTITY(1,1), 
    Nome VARCHAR(50) NOT NULL,
    Email VARCHAR(35) NOT NULL UNIQUE,
    CNPJ CHAR(14) NOT NULL UNIQUE,
    Senha VARCHAR(216),
    Data_Criacao DATETIME,
    Adm_Disponivel BIT,
    UNIQUE (ID, Email, CNPJ),
	PRIMARY KEY (ID)
);

CREATE TABLE GM (
    ID_GM INT IDENTITY(1,1) PRIMARY KEY,
    Email_GM VARCHAR(35) NOT NULL,
    Codigo_Acesso_GM VARCHAR(13),
    Nome_GM VARCHAR(50) NOT NULL,
    Funcao VARCHAR(35) NOT NULL,
    Telefone_GM VARCHAR(15),
    Senha_GM VARCHAR(216),
    FK_ADM_ID INT,
    UNIQUE (Codigo_Acesso_GM, Email_GM, Telefone_GM)
);

CREATE TABLE MESAS (
    ID_Mesa INT IDENTITY(1,1) PRIMARY KEY,
    FK_ADM_ID INT NOT NULL,
    FK_GM_ID_GM INT,
	Nome_Mesa VARCHAR(50),
    QuantidadeMax_Jog INT  NOT NULL,
    Horario_Inicio DATETIME NOT NULL,
    Horario_Fim DATETIME,
    Proxima_Sessao DATETIME NOT NULL,
    Ultima_Sessao DATETIME,
    Anotacoes TEXT,
    Duracao DATETIME,
    Mesa_Disponivel BIT
);

CREATE TABLE JOGADORES (
    ID_jogador INT IDENTITY(1,1) PRIMARY KEY,
    Email_Jogador VARCHAR(35) UNIQUE,
    Nome_Jogador VARCHAR(50) NOT NULL,
    Telefone_Jogador VARCHAR(15)
);

CREATE TABLE FICHA (
    ID_Ficha INT IDENTITY(1,1) PRIMARY KEY,
    FK_JOGADORES_ID INT,
    Nome_Personagem VARCHAR(50),
    Raca_Personagem VARCHAR(20),
    Classe_Personagem VARCHAR(20),
    Criador_Original VARCHAR(50) NOT NULL,
    Ativa INT,
    Atribuida BIT
);

CREATE TABLE MESA_JOGADOR (
    FK_MESAS_ID_Mesa INT,
    FK_JOGADORES_ID_Jogador INT
);
 
CREATE TABLE MESA_FICHA (
    FK_MESAS_ID_Mesa INT,
    FK_FICHA_ID_Ficha INT UNIQUE 
);


ALTER TABLE GM ADD CONSTRAINT FK_GM_2
    FOREIGN KEY (FK_ADM_ID)
    REFERENCES ADMINISTRADORES (ID)
    ON DELETE CASCADE;
 
ALTER TABLE MESAS ADD CONSTRAINT FK_MESAS_2
    FOREIGN KEY (FK_ADM_ID)
    REFERENCES ADMINISTRADORES (ID)
    
 
ALTER TABLE MESAS ADD CONSTRAINT FK_MESAS_3
    FOREIGN KEY (FK_GM_ID_GM)
    REFERENCES GM (ID_GM)
   
 
ALTER TABLE FICHA ADD CONSTRAINT FK_FICHA_2
    FOREIGN KEY (FK_JOGADORES_ID)
    REFERENCES JOGADORES (ID_jogador)
    ON DELETE SET NULL;
 
 
ALTER TABLE MESA_JOGADOR ADD CONSTRAINT FK_MESA_JOGADOR_1
    FOREIGN KEY (FK_MESAS_ID_Mesa)
    REFERENCES MESAS (ID_Mesa)
    ON DELETE CASCADE;
 
ALTER TABLE MESA_JOGADOR ADD CONSTRAINT FK_MESA_JOGADOR_2
    FOREIGN KEY (FK_JOGADORES_ID_Jogador)
    REFERENCES JOGADORES (ID_jogador);

ALTER TABLE MESA_FICHA ADD CONSTRAINT FK_MESA_FICHA_1
    FOREIGN KEY (FK_MESAS_ID_Mesa)
    REFERENCES MESAS (ID_Mesa)
    ON DELETE CASCADE;
 
ALTER TABLE MESA_FICHA ADD CONSTRAINT FK_MESA_FICHA_2
    FOREIGN KEY (FK_FICHA_ID_FICHA)
    REFERENCES FICHA (ID_FICHA);

